// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: network.proto
// Protobuf Java Version: 4.28.3

package burp.Proto;

public final class Network {
  private Network() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Network.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetworkDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetworkData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes rawData = 1;</code>
     * @return The rawData.
     */
    com.google.protobuf.ByteString getRawData();

    /**
     * <code>bool isChunked = 2;</code>
     * @return The isChunked.
     */
    boolean getIsChunked();

    /**
     * <code>int32 chunkNum = 3;</code>
     * @return The chunkNum.
     */
    int getChunkNum();

    /**
     * <code>string traceID = 4;</code>
     * @return The traceID.
     */
    String getTraceID();
    /**
     * <code>string traceID = 4;</code>
     * @return The bytes for traceID.
     */
    com.google.protobuf.ByteString
        getTraceIDBytes();

    /**
     * <code>string serviceHost = 5;</code>
     * @return The serviceHost.
     */
    String getServiceHost();
    /**
     * <code>string serviceHost = 5;</code>
     * @return The bytes for serviceHost.
     */
    com.google.protobuf.ByteString
        getServiceHostBytes();

    /**
     * <code>int32 servicePort = 6;</code>
     * @return The servicePort.
     */
    int getServicePort();

    /**
     * <code>string topic = 7;</code>
     * @return The topic.
     */
    String getTopic();
    /**
     * <code>string topic = 7;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>string reqType = 8;</code>
     * @return The reqType.
     */
    String getReqType();
    /**
     * <code>string reqType = 8;</code>
     * @return The bytes for reqType.
     */
    com.google.protobuf.ByteString
        getReqTypeBytes();
  }
  /**
   * Protobuf type {@code NetworkData}
   */
  public static final class NetworkData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetworkData)
      NetworkDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        NetworkData.class.getName());
    }
    // Use NetworkData.newBuilder() to construct.
    private NetworkData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetworkData() {
      rawData_ = com.google.protobuf.ByteString.EMPTY;
      traceID_ = "";
      serviceHost_ = "";
      topic_ = "";
      reqType_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Network.internal_static_NetworkData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Network.internal_static_NetworkData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetworkData.class, Builder.class);
    }

    public static final int RAWDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes rawData = 1;</code>
     * @return The rawData.
     */
    @Override
    public com.google.protobuf.ByteString getRawData() {
      return rawData_;
    }

    public static final int ISCHUNKED_FIELD_NUMBER = 2;
    private boolean isChunked_ = false;
    /**
     * <code>bool isChunked = 2;</code>
     * @return The isChunked.
     */
    @Override
    public boolean getIsChunked() {
      return isChunked_;
    }

    public static final int CHUNKNUM_FIELD_NUMBER = 3;
    private int chunkNum_ = 0;
    /**
     * <code>int32 chunkNum = 3;</code>
     * @return The chunkNum.
     */
    @Override
    public int getChunkNum() {
      return chunkNum_;
    }

    public static final int TRACEID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object traceID_ = "";
    /**
     * <code>string traceID = 4;</code>
     * @return The traceID.
     */
    @Override
    public String getTraceID() {
      Object ref = traceID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        traceID_ = s;
        return s;
      }
    }
    /**
     * <code>string traceID = 4;</code>
     * @return The bytes for traceID.
     */
    @Override
    public com.google.protobuf.ByteString
        getTraceIDBytes() {
      Object ref = traceID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        traceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEHOST_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object serviceHost_ = "";
    /**
     * <code>string serviceHost = 5;</code>
     * @return The serviceHost.
     */
    @Override
    public String getServiceHost() {
      Object ref = serviceHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceHost_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceHost = 5;</code>
     * @return The bytes for serviceHost.
     */
    @Override
    public com.google.protobuf.ByteString
        getServiceHostBytes() {
      Object ref = serviceHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEPORT_FIELD_NUMBER = 6;
    private int servicePort_ = 0;
    /**
     * <code>int32 servicePort = 6;</code>
     * @return The servicePort.
     */
    @Override
    public int getServicePort() {
      return servicePort_;
    }

    public static final int TOPIC_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object topic_ = "";
    /**
     * <code>string topic = 7;</code>
     * @return The topic.
     */
    @Override
    public String getTopic() {
      Object ref = topic_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 7;</code>
     * @return The bytes for topic.
     */
    @Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTYPE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile Object reqType_ = "";
    /**
     * <code>string reqType = 8;</code>
     * @return The reqType.
     */
    @Override
    public String getReqType() {
      Object ref = reqType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqType_ = s;
        return s;
      }
    }
    /**
     * <code>string reqType = 8;</code>
     * @return The bytes for reqType.
     */
    @Override
    public com.google.protobuf.ByteString
        getReqTypeBytes() {
      Object ref = reqType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!rawData_.isEmpty()) {
        output.writeBytes(1, rawData_);
      }
      if (isChunked_ != false) {
        output.writeBool(2, isChunked_);
      }
      if (chunkNum_ != 0) {
        output.writeInt32(3, chunkNum_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceID_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, traceID_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceHost_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, serviceHost_);
      }
      if (servicePort_ != 0) {
        output.writeInt32(6, servicePort_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, topic_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reqType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, reqType_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!rawData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rawData_);
      }
      if (isChunked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isChunked_);
      }
      if (chunkNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, chunkNum_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceID_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, traceID_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceHost_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, serviceHost_);
      }
      if (servicePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, servicePort_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, topic_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reqType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, reqType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NetworkData)) {
        return super.equals(obj);
      }
      NetworkData other = (NetworkData) obj;

      if (!getRawData()
          .equals(other.getRawData())) return false;
      if (getIsChunked()
          != other.getIsChunked()) return false;
      if (getChunkNum()
          != other.getChunkNum()) return false;
      if (!getTraceID()
          .equals(other.getTraceID())) return false;
      if (!getServiceHost()
          .equals(other.getServiceHost())) return false;
      if (getServicePort()
          != other.getServicePort()) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!getReqType()
          .equals(other.getReqType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RAWDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRawData().hashCode();
      hash = (37 * hash) + ISCHUNKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsChunked());
      hash = (37 * hash) + CHUNKNUM_FIELD_NUMBER;
      hash = (53 * hash) + getChunkNum();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceID().hashCode();
      hash = (37 * hash) + SERVICEHOST_FIELD_NUMBER;
      hash = (53 * hash) + getServiceHost().hashCode();
      hash = (37 * hash) + SERVICEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getServicePort();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReqType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NetworkData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetworkData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetworkData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetworkData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetworkData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetworkData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetworkData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static NetworkData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NetworkData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static NetworkData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetworkData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static NetworkData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetworkData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetworkData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetworkData)
        NetworkDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Network.internal_static_NetworkData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Network.internal_static_NetworkData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetworkData.class, Builder.class);
      }

      // Construct using burp.Proto.Network.NetworkData.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rawData_ = com.google.protobuf.ByteString.EMPTY;
        isChunked_ = false;
        chunkNum_ = 0;
        traceID_ = "";
        serviceHost_ = "";
        servicePort_ = 0;
        topic_ = "";
        reqType_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Network.internal_static_NetworkData_descriptor;
      }

      @Override
      public NetworkData getDefaultInstanceForType() {
        return NetworkData.getDefaultInstance();
      }

      @Override
      public NetworkData build() {
        NetworkData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NetworkData buildPartial() {
        NetworkData result = new NetworkData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(NetworkData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rawData_ = rawData_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isChunked_ = isChunked_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.chunkNum_ = chunkNum_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.traceID_ = traceID_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.serviceHost_ = serviceHost_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.servicePort_ = servicePort_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.topic_ = topic_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.reqType_ = reqType_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetworkData) {
          return mergeFrom((NetworkData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetworkData other) {
        if (other == NetworkData.getDefaultInstance()) return this;
        if (other.getRawData() != com.google.protobuf.ByteString.EMPTY) {
          setRawData(other.getRawData());
        }
        if (other.getIsChunked() != false) {
          setIsChunked(other.getIsChunked());
        }
        if (other.getChunkNum() != 0) {
          setChunkNum(other.getChunkNum());
        }
        if (!other.getTraceID().isEmpty()) {
          traceID_ = other.traceID_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getServiceHost().isEmpty()) {
          serviceHost_ = other.serviceHost_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getServicePort() != 0) {
          setServicePort(other.getServicePort());
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getReqType().isEmpty()) {
          reqType_ = other.reqType_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                rawData_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                isChunked_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                chunkNum_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                traceID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                serviceHost_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                servicePort_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                topic_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                reqType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rawData = 1;</code>
       * @return The rawData.
       */
      @Override
      public com.google.protobuf.ByteString getRawData() {
        return rawData_;
      }
      /**
       * <code>bytes rawData = 1;</code>
       * @param value The rawData to set.
       * @return This builder for chaining.
       */
      public Builder setRawData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        rawData_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rawData = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rawData_ = getDefaultInstance().getRawData();
        onChanged();
        return this;
      }

      private boolean isChunked_ ;
      /**
       * <code>bool isChunked = 2;</code>
       * @return The isChunked.
       */
      @Override
      public boolean getIsChunked() {
        return isChunked_;
      }
      /**
       * <code>bool isChunked = 2;</code>
       * @param value The isChunked to set.
       * @return This builder for chaining.
       */
      public Builder setIsChunked(boolean value) {

        isChunked_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool isChunked = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsChunked() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isChunked_ = false;
        onChanged();
        return this;
      }

      private int chunkNum_ ;
      /**
       * <code>int32 chunkNum = 3;</code>
       * @return The chunkNum.
       */
      @Override
      public int getChunkNum() {
        return chunkNum_;
      }
      /**
       * <code>int32 chunkNum = 3;</code>
       * @param value The chunkNum to set.
       * @return This builder for chaining.
       */
      public Builder setChunkNum(int value) {

        chunkNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkNum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkNum_ = 0;
        onChanged();
        return this;
      }

      private Object traceID_ = "";
      /**
       * <code>string traceID = 4;</code>
       * @return The traceID.
       */
      public String getTraceID() {
        Object ref = traceID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          traceID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string traceID = 4;</code>
       * @return The bytes for traceID.
       */
      public com.google.protobuf.ByteString
          getTraceIDBytes() {
        Object ref = traceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          traceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string traceID = 4;</code>
       * @param value The traceID to set.
       * @return This builder for chaining.
       */
      public Builder setTraceID(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        traceID_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string traceID = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTraceID() {
        traceID_ = getDefaultInstance().getTraceID();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string traceID = 4;</code>
       * @param value The bytes for traceID to set.
       * @return This builder for chaining.
       */
      public Builder setTraceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        traceID_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object serviceHost_ = "";
      /**
       * <code>string serviceHost = 5;</code>
       * @return The serviceHost.
       */
      public String getServiceHost() {
        Object ref = serviceHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serviceHost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serviceHost = 5;</code>
       * @return The bytes for serviceHost.
       */
      public com.google.protobuf.ByteString
          getServiceHostBytes() {
        Object ref = serviceHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceHost = 5;</code>
       * @param value The serviceHost to set.
       * @return This builder for chaining.
       */
      public Builder setServiceHost(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceHost_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceHost = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceHost() {
        serviceHost_ = getDefaultInstance().getServiceHost();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string serviceHost = 5;</code>
       * @param value The bytes for serviceHost to set.
       * @return This builder for chaining.
       */
      public Builder setServiceHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceHost_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int servicePort_ ;
      /**
       * <code>int32 servicePort = 6;</code>
       * @return The servicePort.
       */
      @Override
      public int getServicePort() {
        return servicePort_;
      }
      /**
       * <code>int32 servicePort = 6;</code>
       * @param value The servicePort to set.
       * @return This builder for chaining.
       */
      public Builder setServicePort(int value) {

        servicePort_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 servicePort = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearServicePort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        servicePort_ = 0;
        onChanged();
        return this;
      }

      private Object topic_ = "";
      /**
       * <code>string topic = 7;</code>
       * @return The topic.
       */
      public String getTopic() {
        Object ref = topic_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string topic = 7;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 7;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        topic_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        topic_ = getDefaultInstance().getTopic();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 7;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        topic_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private Object reqType_ = "";
      /**
       * <code>string reqType = 8;</code>
       * @return The reqType.
       */
      public String getReqType() {
        Object ref = reqType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reqType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string reqType = 8;</code>
       * @return The bytes for reqType.
       */
      public com.google.protobuf.ByteString
          getReqTypeBytes() {
        Object ref = reqType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reqType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqType = 8;</code>
       * @param value The reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        reqType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string reqType = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqType() {
        reqType_ = getDefaultInstance().getReqType();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string reqType = 8;</code>
       * @param value The bytes for reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        reqType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetworkData)
    }

    // @@protoc_insertion_point(class_scope:NetworkData)
    private static final NetworkData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetworkData();
    }

    public static NetworkData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetworkData>
        PARSER = new com.google.protobuf.AbstractParser<NetworkData>() {
      @Override
      public NetworkData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetworkData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NetworkData> getParserForType() {
      return PARSER;
    }

    @Override
    public NetworkData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetworkData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetworkData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rnetwork.proto\"\236\001\n\013NetworkData\022\017\n\007rawDa" +
      "ta\030\001 \001(\014\022\021\n\tisChunked\030\002 \001(\010\022\020\n\010chunkNum\030" +
      "\003 \001(\005\022\017\n\007traceID\030\004 \001(\t\022\023\n\013serviceHost\030\005 " +
      "\001(\t\022\023\n\013servicePort\030\006 \001(\005\022\r\n\005topic\030\007 \001(\t\022" +
      "\017\n\007reqType\030\010 \001(\tB\014\n\nburp.Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NetworkData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetworkData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetworkData_descriptor,
        new String[] { "RawData", "IsChunked", "ChunkNum", "TraceID", "ServiceHost", "ServicePort", "Topic", "ReqType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
